apiVersion: v1
kind: Namespace
metadata:
  name: sales
---
apiVersion: v1
kind: Namespace
metadata:
  name: housing
---
apiVersion: v1
kind: Namespace
metadata:
  name: finance
---
apiVersion: v1
kind: Namespace
metadata:
  name: data